services:
  - type: web
    name: calibrate-o1
    runtime: go
    rootDir: backend
    region: oregon
    plan: free
    buildCommand: go build -o server .
    startCommand: ./server
    envVars:
      - key: API_KEY
        sync: false
      - key: DB_HOST
        sync: false
      - key: DB_NAME
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_SSLMODE
        value: disable
