version :"3.9"

services:
    app:
       tty:true
     restart:always
     image:calibrate-o1
     container_name:calibrate-o1
     build :  .
     ports:
        -3000:3000

        env_file:
            - .env
        networks:
              -application
        depeends_on:
            -db:
               condition:service_healthy
        volumes:
         -.:/src/app
        command: air -c .air.toml                  
            


   