version: "3.9"

services:
    app:
        tty: true
        restart: always
        image: calibrate-o1
        container_name: calibrate-o1
        build: .
        ports:
            - 3000:3000
        env_file:
            - .env
        networks:
            - application
        depends_on:
            - db:
                condition: service_healthy
        volumes:
            - .:/src/app
        command: air -c .air.toml                  


    db:
        image: postgres:alpine
        container_name: calibrate-o1-db
        environmnt:
            POSTGRES_USER: ${DB_USER}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_HOST: ${DB_HOST}
            POSTGRES_DB: ${DB_NAME}
        ports:
            - 5432:5432
        volumes:
            -postgres-db:/var/lib/postgresql/data  
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
            interval: 10s
            timeout: 5s
            retries: 5  

networks:
    application:

volumes:
     -postgres-db                

            


   